[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0.213", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4"] }
mongodb = "3.1.0"
dotenv = "0.15"
bson = "2.0"
